In [2]:
import pandas as pd
seoul_starbucks = pd.read_excel('./seoul_starbucks_list.xlsx')
seoul_starbucks.head()

       매장명         위도          경도                               주소       전화번호
0     논현힐탑  37.511558  127.032262          서울특별시 강남구 논현로 648 (논현동)  1522-3232
1      학동역  37.514649  127.030730          서울특별시 강남구 논현로 704 (논현동)  1522-3232
2   차병원사거리  37.508032  127.035373  서울특별시 강남구 봉은사로 213, 센트럴타워 (논현동)  1522-3232
3   논현역사거리  37.510178  127.022223         서울특별시 강남구 강남대로 538 (논현동)  1522-3232
4  강남대로논현R  37.507413  127.022568        서울특별시 서초구 강남대로85길 5 (반포동)  1522-3232

In [3]:
sgg_names=[]
for add in seoul_starbucks['주소']:
    sgg = add.split()[1]
    sgg_names.append(sgg)

sgg_names

['강남구',
 '강남구',
 '강남구',
 '강남구',
 '서초구',
 '강남구',
 '서초구',
 '서초구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강남구',
 '강북구',
 '강북구',
 '강북구',
 '강북구',
 '강북구',
 '강북구',
 '강서구',
 '강서구',
 '강서구',
 '강서구',
 '강서구',
 '강서구',
 '강서구',
 '강서구',
 '강서구',
 '강서구',
 '강서구',
 '강서구',
 '강서구',
 '강서구',
 '강서구',
 '강서구',
 '강서구',
 '강서구',
 '강서구',
 '강서구',
 '강서구',
 '관악구',
 '관악구',
 '관악구',
 '관악구',
 '관악구',
 '관악구',
 '관악구',
 '관악구',
 '관악구',
 '관악구',
 '관악구',
 '광진구',
 '광진구',
 '광진구',
 '광진구',
 '광진구',
 '광진구',
 '광진구',
 '광진구',
 '광진구',
 '광진구',
 '광진구',
 '광진구',
 '광진구',
 '광진구',
 '광진구',
 '광진구',
 '광진구',
 '금천구',
 '금천구',
 '금천구',
 '금천구',
 '금천구',
 '금천구',
 '금천구',
 '금천구',
 '금천구',
 '금천구',
 '금천구',
 '노원구',
 '노원구',
 '노원구',
 '노원구',
 '노원구',
 '노원구',
 '노원구',
 '노원구',
 '노원구',
 '노원구',
 '노원구',
 '노원구',
 '노원구',
 '도봉구',
 '도봉구',
 '도봉구',
 '동작구',
 '동작구',
 '동작구',
 '동작구',
 '동작구',
 '동작구',
 '동작구',
 '동작구',
 '동작구',
 '동작구',
 '동작구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '마포구',
 '서대문구',
 '서대문구',
 '서대문구',
 '서대문구',
 '서대문구',
 '서대문구',
 '서대문구',
 '서대문구',
 '서대문구',
 '서대문구',
 '서대문구',
 '서대문구',
 '서대문구',
 '서대문구',
 '서대문구',
 '서대문구',
 '서대문구',
 '서대문구',
 '서대문구',
 '서대문구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '서초구',
 '성북구',
 '성북구',
 '성북구',
 '성북구',
 '성북구',
 '성북구',
 '성북구',
 '성북구',
 '성북구',
 '성북구',
 '성북구',
 '성북구',
 '성북구',
 '성북구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '송파구',
 '양천구',
 '양천구',
 '양천구',
 '양천구',
 '양천구',
 '양천구',
 '양천구',
 '양천구',
 '양천구',
 '양천구',
 '양천구',
 '양천구',
 '양천구',
 '양천구',
 '양천구',
 '양천구',
 '양천구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '영등포구',
 '은평구',
 '은평구',
 '은평구',
 '은평구',
 '은평구',
 '은평구',
 '은평구',
 '은평구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '종로구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '중구',
 '강동구',
 '강동구',
 '강동구',
 '강동구',
 '강동구',
 '강동구',
 '강동구',
 '강동구',
 '강동구',
 '강동구',
 '강동구',
 '강동구',
 '강동구',
 '강동구',
 '강동구',
 '강동구',
 '구로구',
 '구로구',
 '구로구',
 '구로구',
 '구로구',
 '구로구',
 '구로구',
 '구로구',
 '구로구',
 '구로구',
 '구로구',
 '구로구',
 '동대문구',
 '동대문구',
 '동대문구',
 '동대문구',
 '동대문구',
 '동대문구',
 '동대문구',
 '동대문구',
 '동대문구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '성동구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '용산구',
 '중랑구',
 '중랑구',
 '중랑구',
 '중랑구',
 '중랑구',
 '중랑구',
 '중랑구',
 '중랑구']

In [4]:
seoul_starbucks['시군구명'] = sgg_names

In [5]:
seoul_starbucks

,매장명,위도,경도,주소,전화번호,시군구명
0,논현힐탑,37.511558,127.032262,서울특별시 강남구 논현로 648 (논현동),1522-3232,강남구
1,학동역,37.514649,127.030730,서울특별시 강남구 논현로 704 (논현동),1522-3232,강남구
2,차병원사거리,37.508032,127.035373,"서울특별시 강남구 봉은사로 213, 센트럴타워 (논현동)",1522-3232,강남구
3,논현역사거리,37.510178,127.022223,서울특별시 강남구 강남대로 538 (논현동),1522-3232,강남구
4,강남대로논현R,37.507413,127.022568,서울특별시 서초구 강남대로85길 5 (반포동),1522-3232,서초구
...,...,...,...,...,...,...
573,사가정역,37.579594,127.087966,서울특별시 중랑구 면목로 310,1522-3232,중랑구
574,상봉역,37.596890,127.086470,서울특별시 중랑구 망우로 307 (상봉동),1522-3232,중랑구
575,묵동이마트,37.613433,127.077484,"서울특별시 중랑구 동일로 932 (묵동, 묵동자이아파트) (묵동이마트 B1층)",1522-3232,중랑구
576,묵동,37.615368,127.076633,서울특별시 중랑구 동일로 952,1522-3232,중랑구
577,중화역,37.601709,127.078411,"서울특별시 중랑구 봉화산로 35 1,2층",1522-3232,중랑구

In [6]:
seoul_sgg = pd.read_excel('sgg_pop.xlsx')
seoul_sgg

    시군구명   주민등록인구
0    종로구  159,842
1     중구  135,321
2    용산구  244,953
3    성동구  302,695
4    광진구  361,923
5   동대문구  358,679
6    중랑구  400,989
7    성북구  449,871
8    강북구  313,550
9    도봉구  329,300
10   노원구  529,532
11   은평구  485,842
12  서대문구  323,860
13   마포구  383,494
14   양천구  460,048
15   강서구  589,536
16   구로구  435,751
17   금천구  249,641
18  영등포구  405,982
19   동작구  404,617
20   관악구  514,555
21   서초구  429,995
22   강남구  544,085
23   송파구  676,673
24   강동구  462,275

In [8]:
starbucks_sgg_count = seoul_starbucks.pivot_table(index = '시군구명', values = '매장명', aggfunc = 'count')

In [9]:
starbucks_sgg_count

      매장명
시군구명
강남구    94
강동구    16
강북구     6
강서구    21
관악구    11
광진구    17
구로구    12
금천구    11
노원구    13
도봉구     3
동대문구    9
동작구    11
마포구    32
서대문구   20
서초구    51
성동구    12
성북구    14
송파구    34
양천구    17
영등포구   40
용산구    21
은평구     8
종로구    41
중구     56
중랑구     8

In [10]:
seoul_sgg = pd.merge(seoul_sgg, starbucks_sgg_count, how='left', on='시군구명')
seoul_sgg

    시군구명   주민등록인구  매장명
0    종로구  159,842   41
1     중구  135,321   56
2    용산구  244,953   21
3    성동구  302,695   12
4    광진구  361,923   17
5   동대문구  358,679    9
6    중랑구  400,989    8
7    성북구  449,871   14
8    강북구  313,550    6
9    도봉구  329,300    3
10   노원구  529,532   13
11   은평구  485,842    8
12  서대문구  323,860   20
13   마포구  383,494   32
14   양천구  460,048   17
15   강서구  589,536   21
16   구로구  435,751   12
17   금천구  249,641   11
18  영등포구  405,982   40
19   동작구  404,617   11
20   관악구  514,555   11
21   서초구  429,995   51
22   강남구  544,085   94
23   송파구  676,673   34
24   강동구  462,275   16

In [11]:
seoul_biz = pd.read_excel('sgg_biz.xlsx')
seoul_biz

    시군구명     종사자수    사업체수
0    종로구  265,017  39,952
1     중구  390,530  60,957
2    용산구  141,216  20,813
3    성동구  174,819  27,868
4    광진구  127,879  24,535
5   동대문구  140,748  31,878
6    중랑구  103,016  28,024
7    성북구  108,201  23,287
8    강북구   72,418  18,918
9    도봉구   74,314  18,894
10   노원구  118,713  26,616
11   은평구   90,049  24,873
12  서대문구  109,490  19,796
13   마포구  255,152  37,232
14   양천구  123,311  26,126
15   강서구  248,204  38,524
16   구로구  218,070  38,553
17   금천구  234,012  32,472
18  영등포구  367,557  42,589
19   동작구  112,564  19,916
20   관악구  113,944  26,105
21   서초구  438,733  46,540
22   강남구  694,136  71,373
23   송파구  342,853  47,772
24   강동구  145,990  29,772

In [12]:
seoul_sgg = pd.merge(seoul_sgg, seoul_biz, how='left', on='시군구명')
seoul_sgg

    시군구명   주민등록인구  매장명     종사자수    사업체수
0    종로구  159,842   41  265,017  39,952
1     중구  135,321   56  390,530  60,957
2    용산구  244,953   21  141,216  20,813
3    성동구  302,695   12  174,819  27,868
4    광진구  361,923   17  127,879  24,535
5   동대문구  358,679    9  140,748  31,878
6    중랑구  400,989    8  103,016  28,024
7    성북구  449,871   14  108,201  23,287
8    강북구  313,550    6   72,418  18,918
9    도봉구  329,300    3   74,314  18,894
10   노원구  529,532   13  118,713  26,616
11   은평구  485,842    8   90,049  24,873
12  서대문구  323,860   20  109,490  19,796
13   마포구  383,494   32  255,152  37,232
14   양천구  460,048   17  123,311  26,126
15   강서구  589,536   21  248,204  38,524
16   구로구  435,751   12  218,070  38,553
17   금천구  249,641   11  234,012  32,472
18  영등포구  405,982   40  367,557  42,589
19   동작구  404,617   11  112,564  19,916
20   관악구  514,555   11  113,944  26,105
21   서초구  429,995   51  438,733  46,540
22   강남구  544,085   94  694,136  71,373
23   송파구  676,673   34  342,853  47,772
24   강동구  462,275   16  145,990  29,772

In [13]:
seoul_sgg.to_excel('seoul_sgg.xlsx', index=False)

In [14]:
pip install folium

Collecting folium
  Downloading folium-0.12.1-py2.py3-none-any.whl (94 kB)
     |████████████████████████████████| 94 kB 7.6 MB/s
Requirement already satisfied: requests in /Users/jeongjibaeg/opt/anaconda3/lib/python3.8/site-packages (from folium) (2.25.1)
Requirement already satisfied: numpy in /Users/jeongjibaeg/opt/anaconda3/lib/python3.8/site-packages (from folium) (1.20.1)
Collecting branca>=0.3.0
  Downloading branca-0.4.2-py3-none-any.whl (24 kB)
Requirement already satisfied: jinja2>=2.9 in /Users/jeongjibaeg/opt/anaconda3/lib/python3.8/site-packages (from folium) (2.11.3)
Requirement already satisfied: MarkupSafe>=0.23 in /Users/jeongjibaeg/opt/anaconda3/lib/python3.8/site-packages (from jinja2>=2.9->folium) (1.1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/jeongjibaeg/opt/anaconda3/lib/python3.8/site-packages (from requests->folium) (1.26.4)
Requirement already satisfied: idna<3,>=2.5 in /Users/jeongjibaeg/opt/anaconda3/lib/python3.8/site-packages (from requests->folium) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /Users/jeongjibaeg/opt/anaconda3/lib/python3.8/site-packages (from requests->folium) (2020.12.5)
Requirement already satisfied: chardet<5,>=3.0.2 in /Users/jeongjibaeg/opt/anaconda3/lib/python3.8/site-packages (from requests->folium) (4.0.0)
Installing collected packages: branca, folium
Successfully installed branca-0.4.2 folium-0.12.1
Note: you may need to restart the kernel to use updated packages.

In [15]:
import pandas as pd
import folium
import json

In [ ]:
seoul_starbucks = pd.